version: '3'

services:
  shortner:
    image: urlshortner
    container_name: urlshortner
    hostname : urlshortner
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: >
      bash -c "
      /usr/bin/supervisord
      && /usr/bin/supervisorctl stop all
      && /usr/bin/supervisorctl start shortner
      && sleep infinity"
    volumes:
      - /var/log/UrlShortner:/var/log/UrlShortner:rw
    ports:
      - "5000:5000"
